services:
  - type: web
    name: django-website
    env: python
    buildCommand: ""
    startCommand: gunicorn yourprojectname.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: yourprojectname.settings
